	Globals.DEBUG = true;

	Globals.DEBUG_POPUP = true;

	Globals.DEBUG_SOCIAL_MANAGER_SERVER = true;

	Globals.DEBUG_SETTINGS = true;

	Globals.DEBUG_POPUP_TESTOLOGY = true;

	Globals.DEBUG_USE_ONLINESETTINGS_TESTTIME = true;

	Globals.DEBUG_USE_ONLINESETTINGS_SET = true;

	Globals.DEBUG_FREE_PURCHASES = true;

	Globals.DEBUG_ALL_CHARS = true;

	Globals.DEBUG_ALL_BOARDS = true;

	Globals.DEBUG_DISPLAY_ALL_CHARS = true;

	Globals.DEBUG_DISPLAY_ALL_BOARDS = true;

	Globals.DEBUG_FREE_INAPP_PURCHASE = true;

	Globals.DEBUG_SKIP_VIDEO_ADS = true;

	Globals.DEBUG_DISABLE_HOVERBOARD = true;

	Globals.DEBUG_DISABLE_JETPACK = true;

	Globals.DEBUG_SKIP_TUTORIAL_IN_EDITOR = true;

	Globals.DEBUG_USE_DEBUG_LOGIN_STATE = true;

	Globals.DEBUG_USE_FAKE_ONLINE_SETTINGS = true;

	Globals.DEBUG_USE_FAKE_NEW_ONLINE_SETTINGS = true;

	Globals.DEBUG_ENABLE_WATERMARK = true;

	Globals.DEBUG_OVERRIDE_ONLINE_SETTINGS_URL = true;

	Globals.DEBUG_OVERRIDE_NEW_ONLINE_SETTINGS_URL = true;

	Globals.DEBUG_USE_TEST_AD_CONSTANTS = true;

	Globals.DEBUG_SHOW_FRONT_SCREEN_IF_NEW_USER = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDERS = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDER_CHARTBOOST = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDER_INMOBI = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDER_SUPERSONIC = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDER_FACEBOOK = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDER_MOBVISTA = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDERS_IGNORE_GRACE_PERIOD = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDERS_IGNORE_TIME_LIMIT = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDERS_IGNORE_IMPRESSION_LIMIT = true;

	Globals.DEBUG_INTERSTITIAL_PROVIDERS_IGNORE_IN_APP_PURCHASES = true;

	Globals.DEBUG_INTERSTITIAL_IN_EDITOR = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_ADCOLONY = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_VUNGLE = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_TAPJOY = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_INMOBI = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_CHARTBOOST = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_SUPERSONIC = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_FACEBOOK = true;

	Globals.DEBUG_VIDEOADS_PROVIDERS_MOBVISTA = true;

	Globals.DEBUG_USE_CELEBRATION_TESTER = true;

	Globals.DEBUG_USE_EVENT_TESTER = true;

	Globals.DEBUG_SHOW_PERFORMANCE_INFO = true;

	Globals.DEBUG_USE_TIMESCALE_PAUSE_BUTTON = true;

	Globals.DEBUG_ENABLE_SALES = true;

	Globals.DEBUG_ENABLE_HOLIDAY_SALES = true;

	Globals.DEBUG_ENABLE_NEW_YEAR_SALES = true;

	Globals.DEBUG_ENABLE_BLACK_FRIDAY_SALES = true;

	Globals.DEBUG_DISABLE_NOTIFICATION_REQUEST = true;

	Globals.DEBUG_TEST_FPS_SPIKES = true;

	Globals.DEBUG_USE_DEBUG_AD_PROVIDER = true;

	Globals.DEBUG_PROMO_CODE_SAVE_DISABLE = true;

	Globals.DEBUG_PROMO_CODE_ID_SAVE_DISABLE = true;

	Globals.DEBUG_PROMO_CODE_TEST_ENVIRONMENT = true;

	Globals.DEBUG_ENABLE_BOARD_BUNDLE = true;

	Globals.DEBUG_AD_SYSTEM_SINGLE_IMPRESSION = true;

	Globals.DEBUG_IGNORE_PROMOTION_EXPIRATION = true;

	Globals.DEBUG_FORCE_SPECIFIC_LOCALE = true;

	Globals.DEBUG_ENABLE_LOADING_DELAY = true;

	Globals.DEBUG_LOADING_DELAY_SECONDS = 0.5f;

	Globals.DEBUG_USE_DEBUG_LOGS_INSTEAD_OF_FLURRY = true;

	Globals.DEBUG_FACEBOOK_SESSION_WARNINGS = true;

	Globals.DEBUG_DEVICE_UTILITY_WARNINGS = true;

	Globals.DEBUG_STRINGS_CLASS_WARNINGS = true;

	Globals.DEBUG_SHADERS = true;

	Globals.DEBUG_CHARACTER_INVINCIBLE = true;

	Globals.DEBUG_CHARACTER_MOVE_THROUGH_COLLIDERS = true;

	Globals.DEBUG_LIMITED_CHARACTER_POPUP = true;

	Globals.DEBUG_LIMITED_CHARACTER_POPUP_IGNORE_EXPIRE = true;

	Globals.DEBUG_LIMITED_BOARD_POPUP = true;

	Globals.DEBUG_LIMITED_BOARD_POPUP_IGNORE_EXPIRE = true;

	Globals.DEBUG_FIRST_PURCHASE_BONUS = true;

	Globals.DEBUG_ENABLE_WELCOME_PACK = true;

	Globals.DEBUG_ENABLE_GET_2_KEYS = true;

	Globals.DEBUG_ARE_NOTIFICATIONS_ENABLED = true;

	Globals.DEBUG_TEMPERATURE_METRIC_DISABLED = true;

	Globals.DEBUG_ONLINE_SAVE_PEEK_ENABLED = true;

	Globals.DEBUG_USE_ENABLE_SS_EVENT_TYPE___SUPER_MYSTERY_BOX = true;

	Globals.DEBUG_USE_ENABLE_SS_EVENT_TYPE___MYSTERY_POWER_UP = true;

	Globals.DEBUG_USE_ENABLE_SS_EVENT_TYPE___LETTER_HUNT_CHARACTER = true;

	Globals.DEBUG_SKIP_DAILY_LETTERS = true;

	Globals.DEBUG_USE_ENABLE_PLAYER_INFO___IS_ACTIVE_DAILY_LETTER_EVENT = true;

	Globals.DEBUG_USE_ENABLE_PLAYER_INFO___HAS_DAILY_WORD_TIME_LEFT = true;

	Globals.DEBUG_USE_DEBUG_DAILYWORD = true;

	Globals.DEBUG_IS_HOVERBOARD_ALWAYS_REWARDED_FOR_MYSERY_POWERUP = true;