ARCHS = armv7 arm64

include theos/makefiles/common.mk

TWEAK_NAME = DungeonHunter4Cheats
DungeonHunter4Cheats_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk


SUBPROJECTS += dungeonhunter4cheats
include $(THEOS_MAKE_PATH)/aggregate.mk
